import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Sorry Robots: A Full-Stack Product Design Firm</title>
        <meta content="Sorry Robots: A Full-Stack Product Design Firm" name="title" />
        <meta content="We’re a full-stack product design firm and 3PL. We’re not reinventing the wheel, but everything else is fair game." name="description"></meta>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className="new-menu">
          <div className="logo-wrapper">
            <a href="index.html" aria-current="page" className="goto_home">
              <Image src="/images/Sorry-Robots-Logo-2000.webp" width={98}  height={17} alt="Sorry Robots: A Full-Stack Product Design Firm" layout="responsive" />
            </a>
          </div>
          <div className="new-menu-links">
            <ul>
              <li><a href="index.html" class="goto_founder navlink1">Meet our Founder</a></li>
              <li><a href="index.html" class="goto_work navlink1">Work</a></li>
              <li><a href="index.html" class="gotocontact navlink1">Contact</a></li>
            </ul>
          </div>
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
